[package]
name = "supermatter-rs"
version = "0.1.0"
authors = ["Colm Hickey <colmohici@gmail.com>"]
license = "Apache-2.0"

[dependencies]
rustc-serialize = "0.3"
libc = "0.2"
kernel32-sys = "0.2"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"
